// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {ZKVerifier} from "../src/ZKVerifier.sol";

/// @notice Dedicated tests for real Groth16 verification using proofs
///         generated by snarkjs for the CollateralThreshold(10) circuit.
contract ZKVerifierRealTest is Test {
    ZKVerifier public verifier;

    // ── Real proof from zk-circuits/build/CollateralThreshold/proof.json ──
    // B-point coordinates swapped per snarkjs → Solidity convention
    uint256[2] validA = [
        uint256(7501418155070697957886445575060222213855214501275462131512066891886260797522),
        uint256(20307960349622408087724662811457557377081981738727894655014255382300019349183)
    ];
    uint256[2][2] validB = [
        [
            uint256(10090863171021850233060917308111442514293021448090904360733241435633950134456),
            uint256(20514319163820469606716028119004784496615796526046539688792089896488849842644)
        ],
        [
            uint256(20328077676924037459990755442354571662269605852107790438311474812910010595491),
            uint256(282098938794764696965769496268380771436106555603842946113396473292615518483)
        ]
    ];
    uint256[2] validC = [
        uint256(15188614206463563129152732570408292639008973769821094020924759466080418510005),
        uint256(3210483392407363850290683052617417594252216771062307497254862380087632713208)
    ];

    // Public signals from public.json: [commitment, sufficient, threshold]
    function _validPubSignals() internal pure returns (uint256[] memory) {
        uint256[] memory sigs = new uint256[](3);
        sigs[0] = 10701395941502774979696515461883671971228744800004823607239438080880607796877;
        sigs[1] = 1;
        sigs[2] = 100000000000000000000; // 100e18
        return sigs;
    }

    function setUp() public {
        verifier = new ZKVerifier();
    }

    // ════════════════════════════════════════════════════════════════
    //  POSITIVE TESTS — real proof should verify
    // ════════════════════════════════════════════════════════════════

    function test_realProof_verifies() public view {
        uint256[] memory sigs = _validPubSignals();
        bool result = verifier.verifyProof(validA, validB, validC, sigs);
        assertTrue(result, "Valid Groth16 proof must verify");
    }

    function test_numPublicSignals() public view {
        assertEq(verifier.NUM_PUBLIC_SIGNALS(), 3);
    }

    // ════════════════════════════════════════════════════════════════
    //  NEGATIVE TESTS — tampered proofs/signals should fail
    // ════════════════════════════════════════════════════════════════

    function test_invalidProof_fakeA() public view {
        uint256[2] memory fakeA = [uint256(1), uint256(2)];
        uint256[] memory sigs = _validPubSignals();
        bool result = verifier.verifyProof(fakeA, validB, validC, sigs);
        assertFalse(result, "Tampered A point must fail");
    }

    function test_invalidProof_fakeB() public view {
        uint256[2][2] memory fakeB = [
            [uint256(1), uint256(2)],
            [uint256(3), uint256(4)]
        ];
        uint256[] memory sigs = _validPubSignals();
        bool result = verifier.verifyProof(validA, fakeB, validC, sigs);
        assertFalse(result, "Tampered B point must fail");
    }

    function test_invalidProof_fakeC() public view {
        uint256[2] memory fakeC = [uint256(1), uint256(2)];
        uint256[] memory sigs = _validPubSignals();
        bool result = verifier.verifyProof(validA, validB, fakeC, sigs);
        assertFalse(result, "Tampered C point must fail");
    }

    function test_invalidPubSignals_wrongValues() public view {
        uint256[] memory sigs = new uint256[](3);
        sigs[0] = 999;
        sigs[1] = 1;
        sigs[2] = 100e18;
        bool result = verifier.verifyProof(validA, validB, validC, sigs);
        assertFalse(result, "Wrong public signals must fail");
    }

    function test_invalidPubSignals_wrongCount() public view {
        uint256[] memory sigs = new uint256[](1);
        sigs[0] = 42;
        bool result = verifier.verifyProof(validA, validB, validC, sigs);
        assertFalse(result, "Wrong signal count must return false");
    }

    function test_invalidPubSignals_empty() public view {
        uint256[] memory sigs = new uint256[](0);
        bool result = verifier.verifyProof(validA, validB, validC, sigs);
        assertFalse(result, "Empty signals must return false");
    }

    function test_invalidPubSignals_tooMany() public view {
        uint256[] memory sigs = new uint256[](5);
        bool result = verifier.verifyProof(validA, validB, validC, sigs);
        assertFalse(result, "Too many signals must return false");
    }

    function test_invalidPubSignals_outOfField() public view {
        uint256[] memory sigs = new uint256[](3);
        // SNARK_SCALAR_FIELD value (>= field) should fail
        sigs[0] = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
        sigs[1] = 1;
        sigs[2] = 100e18;
        bool result = verifier.verifyProof(validA, validB, validC, sigs);
        assertFalse(result, "Signal >= scalar field must return false");
    }

    // ════════════════════════════════════════════════════════════════
    //  REPLAY PREVENTION TESTS
    // ════════════════════════════════════════════════════════════════

    function test_markProofUsed_andReplay() public {
        verifier.authorizeCaller(address(this));

        bytes32 proofHash = keccak256("unique-proof");
        assertFalse(verifier.isProofUsed(proofHash));

        verifier.markProofUsed(proofHash, 0);
        assertTrue(verifier.isProofUsed(proofHash));
        assertEq(verifier.vaultNonce(address(this)), 1);

        vm.expectRevert(ZKVerifier.ProofAlreadyUsed.selector);
        verifier.markProofUsed(proofHash, 1);
    }

    function test_nonce_mustMatch() public {
        verifier.authorizeCaller(address(this));

        vm.expectRevert(ZKVerifier.InvalidNonce.selector);
        verifier.markProofUsed(keccak256("nonce-test"), 5); // nonce is 0, not 5
    }

    function test_unauthorizedCaller_reverts() public {
        vm.prank(makeAddr("random"));
        vm.expectRevert(ZKVerifier.NotAuthorized.selector);
        verifier.markProofUsed(keccak256("test"), 0);
    }
}
